name: Test Casks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Syntax check the applescript launcher and ensure it's executable
        run: ./FORScan.app/Contents/MacOS/FORScan syntax-check

      - name: Syntax check the Info.plist
        run: plutil FORScan.app/Contents/Info.plist

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      
      # Tap allows custom URL as 3rd parameter and knows how to use file paths
      - run: brew tap onnimonni/tap .
      
      # Should test the command that we actually want to test and advertise
      - run: brew install --no-quarantine --cask wine-stable onnimonni/tap/forscan
